tweak week util

diff --git a/utils/week b/utils/week
--- a/utils/week
+++ b/utils/week
@@ -1,8 +1,55 @@
 #!/bin/bash
+
 root_path="$HOME/Jottacloud/week"
 year_path="$root_path/$(date +%Y)"
 mkdir -p "$year_path"
 
+usage=$(
+  cat <<EOF
+Usage: week
+  -e[dit instead of print]
+  -c[onfig week template]
+  -t[oday] -s[hutdown]
+  -n[otes for this week]
+  -o[verview of all notes]
+  -a[ll weeks]
+  -i[nbox {something}]
+  {@Keyword[ to grep]}
+
+  -e[dit]:
+  Use this flag (first!) to open output in vim instead of printing to stdout. Only applicable as standalone (to edit week) or combined with -c or -n.
+
+  -[c]onfig:
+  Config week template. Prefix with -e to edit.
+
+  -t[oday]:
+  Output only today\'s agenda (excluding Shutdown routine)
+
+  -s[hutdown]:
+  Output only today\'s shutdown routine.
+
+  -n[otes for this week]:
+  Open up this week\'s notes file (create if it doesn\'t exist).
+
+  -o[verview of all notes]:
+  Combine all notes into a single RO temp file (you can follow links to the source file to edit notes).
+
+  -a[ll weeks]:
+  Combine all weeks and notes into a single RO temp file (you can follow links to the source file to edit notes).
+
+  -i[nbox {something}]:
+  Create a new {something} task and add to this week\'s inbox.
+
+  @Keyword:
+  Filter input (ie | grep @Keyword) before printing
+
+  -h[elp]:
+  Show usage.
+
+EOF
+)
+
+# Hack to utilize coreutils on mac
 if command -v ghead &>/dev/null; then
   function head() {
     ghead $*
@@ -16,6 +63,15 @@ if command -v ghead &>/dev/null; then
     gsed $*
   }
 fi
+
+# Require GNU versions of head, date, sed
+array=(head date sed)
+for i in "${array[@]}"; do
+  if ! grep -q "GNU" <<<"$($i --version)"; then
+    echo "Missing GNU $i, aborting"
+    exit 1
+  fi
+done
 
 default_week=$(
   cat <<EOF
@@ -45,6 +101,7 @@ previous_week="$year_path/$(($(date +%U) - 1)).md"
 if [[ ! -e "$current_week" ]]; then
   cat "$week_template" >"$current_week"
 
+  # rollover unfinished tasks (- [ ])
   if [[ -e "$previous_week" ]]; then
     cat "$previous_week" | grep "\[ " | sed 's/^/(Previous week) /' >>"$current_week"
   fi
@@ -53,18 +110,49 @@ fi
 today="$(date +%A)"
 next_day_or_inbox="$(date --date=tomorrow +%A | sed 's/Saturday/Inbox/g')"
 
-while getopts 'ctsi:' flag; do
+# Allow filtering on keyword tags (with '@' prefix)
+filter=tee
+tags="$(echo "$@" | grep -o '@\w\+')"
+if [[ ! -z $tags ]]; then
+  filter="grep $tags"
+fi
+
+while getopts 'hectsnoai:' flag; do
   case "${flag}" in
+  h)
+    echo "$usage"
+    exit 0
+    ;;
+  e)
+    cmd=vim
+    ;;
   c)
-    $EDITOR "$week_template"
+    $cmd "$week_template"
     exit 0
     ;;
   t)
-    awk "/$today/, /$next_day_or_inbox/" "$current_week" | head -n -1 | grep -v 'Shutdown\|  '
+    awk "/$today/, /$next_day_or_inbox/" "$current_week" | head -n -1 | $filter | grep -v 'Shutdown\|  '
     exit 0
     ;;
   s)
-    awk "/$today/, /$next_day_or_inbox/" "$current_week" | head -n -1 | grep 'Shutdown\|  '
+    awk "/$today/, /$next_day_or_inbox/" "$current_week" | head -n -1 | $filter | grep 'Shutdown\|  '
+    exit 0
+    ;;
+  n)
+    notes_file="${current_week/.md/.notes.md}"
+    if [[ ! -e "$notes_file" ]]; then
+      echo "# Notes" >>$notes_file
+      echo "# Ideas" >>$notes_file
+    fi
+    $cmd "$notes_file"
+    exit 0
+    ;;
+  o)
+    tail -n +1 $root_path/**/*.notes.md | sed 's/^#/##/g' | sed 's/==>/#/g' | sed 's/<==//g' | $filter | view -c 'set filetype=markdown' -
+    exit 0
+    ;;
+  a)
+    tail -n +1 $root_path/**/*.md | sed 's/#/##/g' | sed 's/==>/#/g' | sed 's/<==//g' | $filter | view -c 'set filetype=markdown' -
     exit 0
     ;;
   i)
@@ -74,10 +162,10 @@ while getopts 'ctsi:' flag; do
     exit 0
     ;;
   *)
-    echo "invalid flag"
+    echo "$usage"
     exit 1
     ;;
   esac
 done
 
-$EDITOR "$current_week"
+$cmd "$current_week"
